-- =====================================================
-- 01_create_database_and_schema.sql
-- KnowledgeOps AI database and schema
-- =====================================================

-- Step 1 — Create Database

CREATE DATABASE IF NOT EXISTS KNOWLEDGEOPS_AI;


-- Step 2 — Create Schema

CREATE SCHEMA IF NOT EXISTS KNOWLEDGEOPS_AI.DOCS;


-- Step 3 — Grant permissions to App Role

GRANT USAGE ON DATABASE KNOWLEDGEOPS_AI
TO ROLE KNOWLEDGEOPS_APP_ROLE;


GRANT USAGE ON SCHEMA KNOWLEDGEOPS_AI.DOCS
TO ROLE KNOWLEDGEOPS_APP_ROLE;


GRANT CREATE TABLE ON SCHEMA KNOWLEDGEOPS_AI.DOCS
TO ROLE KNOWLEDGEOPS_APP_ROLE;


GRANT CREATE STAGE ON SCHEMA KNOWLEDGEOPS_AI.DOCS
TO ROLE KNOWLEDGEOPS_APP_ROLE;


GRANT CREATE VIEW ON SCHEMA KNOWLEDGEOPS_AI.DOCS
TO ROLE KNOWLEDGEOPS_APP_ROLE;


GRANT CREATE PROCEDURE ON SCHEMA KNOWLEDGEOPS_AI.DOCS
TO ROLE KNOWLEDGEOPS_APP_ROLE;


-- Step 4 — Verify

SHOW DATABASES LIKE 'KNOWLEDGEOPS_AI';

SHOW SCHEMAS IN DATABASE KNOWLEDGEOPS_AI;